function [ipcByOrder, totalIPC, detailTable] = ...
    computeIPC_legendreNoZeroDup_sweepPrint(X, u, dsmaxPairs, ...
                                            param1_name, param1_val, ...
                                            param2_name, param2_val)
% A wrapper that calls computeIPC_legendreNoZeroDup, but prints
% param name & value in the header. 

    % We just call the real function
    [ipcByOrder, totalIPC, detailTable] = ...
        computeIPC_legendreNoZeroDup(X, u, dsmaxPairs);

    fprintf('\nIPC Calculation for %s=%.3g, %s=%.3g  =>  totalIPC=%.4f\n',...
            param1_name, param1_val, param2_name, param2_val, totalIPC);
end
